### ISSUE TITLE
Authorization per policy

### ISSUE THREAD

**Issue by clairernovotny** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#17]
The sample should show how to use ASP.NET Core's authorization policies to work with B2C's journeys to specify that specific policies are required for certain authorization.

That will enable things like step-up to MFA by using an attribute like `Authorize(Policy="mfa")`, and have it automatically redirect to the MFA journey to do the step-up.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
