### ISSUE TITLE
Show how to execute additional policies once the user is already logged in

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#2]
If you try to invoke any policy via the `ChallengeAsync` call after the user is already signed in, you might find that ASP.NET redirects to the "Forbidden" path of the underlying cookie middleware, instead of redirecting to Azure AD B2C.

To get the desired behavior, change the `ChallengeAsync` call to the following:

``` C#
await HttpContext.Authentication.ChallengeAsync(Startup.ProfilePolicyId.ToLower(), authenticationProperties, Microsoft.AspNetCore.Http.Features.Authentication.ChallengeBehavior.Unauthorized);
```

See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L346 for detail.

**Comment by dstrockis** [comment]
Looks like this workaround is to be fixed/removed in a future version of the middleware: https://github.com/aspnet/Security/pull/980

**Comment by Bigshooter** [comment]
@dstrockis I attempted your fix and I no longer receive the Forbidden message, however I now get https://websiteURL/B2C_1_policysigninsignup .... any direction would be a great help.

**Comment by Bigshooter** [comment]
Took some time but I figured it out.  I did not add my dev redirect URL for editing a profile to azure B2C redirect URLS.

**Comment by gsacavdm** [comment]
@dstrockis even after updating to 1.1 this still seems to be necessary.
See #15 

Is the expectation that we should not need the ChallengeBehavoir?

**Comment by danroth27** [comment]
@tratcher @haok

**Comment by nhwilly** [comment]
It looks like you all are working on this really neat capability.  It would great if someone could author a blog post on how to do it correctly.  I've chased my tail for days and I can't get the behavior I want.  Mostly because I'm not entirely sure I know what's going on under the covers.  Thanks...

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
