### ISSUE TITLE
Policies should be lowercase only

### ISSUE THREAD

**Issue by Kaimonos** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#21]
I copied the policy names from the portal, where they are cased. I changed the line

context.ProtocolMessage.IssuerAddress = context.ProtocolMessage.IssuerAddress.Replace(defaultPolicy, policy);
                
to 

context.ProtocolMessage.IssuerAddress = context.ProtocolMessage.IssuerAddress.ToLower().Replace(defaultPolicy.ToLower(), policy.ToLower());

**Comment by gsacavdm** [comment]
Actually, you don't need to do a ToLower on them. If you send them as they are in the portal (with upper case) the sample still works just fine.

**Comment by gsacavdm** [comment]
I stand corrected, my apologies @Kaimonos, we'll get this fixed.

**Comment by gsacavdm** [comment]
Fixed! Thanks again @Kaimonos.
