### ISSUE TITLE
How essential is SessionState?

### ISSUE THREAD

**Issue by ry8806** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#22]
I've not dug into the code fully yet, however can see a few references to SessionState

I'd like to use Azure AD B2C, however I'm a bit reluctant of bringing in SessionState into my current application.

Are there any other samples which don't rely on SessionState, or is SessionState essential to run Azure AD B2C??

Thanks
Ryan

**Comment by gsacavdm** [comment]
Hey @ry8806, updated the sample's read me with an "About the code section", in it you should find this note:

> MSALSessionCache is a sample implementation of a custom MSAL token cache, which saves tokens in the current HTTP session. In a real-life application, you would likely want to save tokens in a long lived store instead, so that you don't need to retrieve new ones more often than necessary.
