### ISSUE TITLE
AcquireTokenSilentAsync: result.AccessToken == null on my own B2C

### ISSUE THREAD

**Issue by NikolaosWakem** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#23]
as long as you dont use custom domains - it will work

add key="ida:Tenant" value="[only use this syntax!!].onmicrosoft.com"

**Comment by jaxxon33** [comment]
I'm no expert but I would check your apps Reply URL. I've been adapting my tenant to a few different apps and it's the one thing that stops it working for me.

![screen shot 2017-05-18 at 10 40 44 am](https://cloud.githubusercontent.com/assets/1849877/26181846/d1412308-3bb6-11e7-928b-b5dff5269f40.png)
![screen shot 2017-05-18 at 10 41 32 am](https://cloud.githubusercontent.com/assets/1849877/26181848/d4559e34-3bb6-11e7-8ca5-2bb94069bb22.png)
![screen shot 2017-05-18 at 10 42 20 am](https://cloud.githubusercontent.com/assets/1849877/26181851/d8ec8a70-3bb6-11e7-9587-66d60ac6fbe6.png)

**Comment by garethrampton** [comment]
@NikolaosWakem I'm seeing exactly the same issue. My configuration is correct (as it is documented), and I don't believe this is related to the reply url - it appears to be related to scopes, but I'm not sure what the solution is right now, and the Azure portal doesn't give the option of adding access related token scopes either.

**Comment by allenhula** [comment]
@NikolaosWakem This sample works fine for me. Suggest you capture request using Fiddler and find out what's wrong. 
@garethrampton Yes, the code is not matching the readme guideline. You need to register another web api application, and define scope, then grant api access to the web app application. All these steps can be done on portal. Suggest you follow steps in this [article](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-api-dotnet).

**Comment by NikolaosWakem** [comment]
![image](https://cloud.githubusercontent.com/assets/4430381/26242655/14308526-3c81-11e7-93cb-24159ac5adf3.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26242679/311a84fc-3c81-11e7-8767-320b785a9a8c.png)

https://localhost:44316/signin-oidc 

![image](https://cloud.githubusercontent.com/assets/4430381/26242755/6f2cf068-3c81-11e7-9cf8-e420c11ee128.png)

Do you see the scopes returned in your id_token?

**Comment by gsacavdm** [comment]
@NikolaosWakem , can you share details on what the issue was. I'd like to see if there's anything we can update to prevent people from running into the same issue.

**Comment by parakhj** [comment]
@NikolaosWakem is using a tenant that has an additional domain name (mydomain.com) connected to the Azure AD B2C tenant (mydomain.onmicrosoft.com). Using mydomain.com as the tenant name in the request URL causes our service to prevent returning access_tokens (although id_tokens are returned just fine)

**Comment by NikolaosWakem** [comment]
Thanks for you help in tracking this dow

I've wasted at least 30-40 hours finding this out the hard way over the last 3 weeks so let's fix it or thoroughly document it. Scope must be vanity name, authority must not be vanity names for access tokens to work

**Comment by garethrampton** [comment]
I still can't get this to work. I never receive an Access token although I receive an Id token fine.
@allenhula I followed the steps in the linked article which is how I'd had things set up anyway.

Anyone have any pointers on how to get this working - or can provide a sample configuration?

The other thing I see - is when auth'ing directly via my web app the auth process works as expected (minus the ability to get an access token), but if I try using any variation of the "run now" link from the Azure portal I get a remote failure with the error that the message.state is null or empty.

**Comment by parakhj** [comment]
@garethrampton can you elaborate more on the "any variation of the run now link". Also, can you share the correlation ID when you hit the failure?

**Comment by garethrampton** [comment]
Quick update - finally managed to get this to work after removing and re-adding my application from Azure B2C and then making sure my scopes were configured correctly. It does not appear to work without specifically defining custom scopes - the default user_impersonation scope alone will not provide an access token.
