### ISSUE TITLE
Getting AADB2C90081 error

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#25]
Hi,

I followed the steps and after successful authentication i am getting following error; i see ClientSecret specified in the application.json file
AADB2C90081: The specified client_secret does not match the expected value for this client. Please correct the client_secret and try again.
Correlation ID: e1d3a273-1e64-40ab-bcb2-53768f5f5d5b
Timestamp: 2017-05-22 17:45:45Z

**Comment by parakhj** [comment]
@rahulvmarathe did you update the original values in the sample? And if so, did you generate a new client secret in the Azure AD B2C portal and update the value accordingly in the sample?

**Comment by Marren85** [comment]
I find the documentation about B2C extremely poor, to get the Client Secret, if you didn't know:

Log into the Azure portal, go to your B2C blade settings and click "Applications" which I assume you have already set up...click the app you've set up that your using...click "Keys"...Generate Key....Save

That's your Client Secret, copy and paste it into VS...

I've found if the Client Secret it generates contains dodgy characters such as * / { etc its temperamental, generate another and your good to go...

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
