### ISSUE TITLE
VS2017 error occurs on project run

### ISSUE THREAD

**Issue by herbat73** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#26]
> An error occured attempting to determine the process id of dotnet.exe which is hosting your application. One or more errors occured.

To get rid this error follow and install script in powershell
https://support.microsoft.com/en-us/help/3180222/warnings-about-an-untrusted-certificate-after-you-install-visual-studio-2015-update-3

**Comment by Marren85** [comment]
Hi, I had this the other day, not 100% on how I fixed it but I think it was because in the properties of my project in Visual Studio, I had a https url in the "App URL" address on the Debug page. I changed that back to http. changed my launch url to https and was good to go

**Comment by clockworkmice** [comment]
It is to do with untrusted certificates yes. I fixed with https://blogs.msdn.microsoft.com/robert_mcmurray/2013/11/15/how-to-trust-the-iis-express-self-signed-certificate/ old skool 😆
