### ISSUE TITLE
Best add option.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

### ISSUE THREAD

**Issue by NikolaosWakem** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#33]
I suggest you maybe add 

option.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

to get around dotnet crashing on access denied in netcore 2.0

https://github.com/aspnet/Security/issues/1376

**Comment by markwest51** [comment]
in .net core 2.0, i had to set this to 

services.AddAuthentication(
                sharedOptions => sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

The SignInScheme was no longer available ?

**Comment by NikolaosWakem** [comment]
I have this live in net core 2.0..

using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Identity.Client;
using System.Security.Claims;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Authentication.Cookies;


            public void Configure(string name, OpenIdConnectOptions options)
            {
                **options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;**
                options.ClientId = AzureAdB2COptions.ClientId;
                options.Authority = AzureAdB2COptions.Authority;

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
