### ISSUE TITLE
Asp.Net Core 2 - get these build errors when incorporating into my own Web API

### ISSUE THREAD

**Issue by markwest51** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#34]
hi

Does this need updating to work in ASP.NET Core 2.0 Web API, taking the code into my own solution to protect an API which will eventually be called by a Web App, the Azure B2C is all setup and correct.  In the OpenIdConnectOptionsSetup class i get the following errors flagged up 

![image](https://user-images.githubusercontent.com/16761127/30404108-da4b42a2-98dc-11e7-9cce-6e13fe0e8cb9.png)

Do i need to reference IdentityClient still ? 

cheers

**Comment by parakhj** [comment]
Check out this branch: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp/tree/core2.0

**Comment by NikolaosWakem** [comment]
I use this is .net core 2.0

public async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
            {
                var code = context.ProtocolMessage.Code;
                var userTokenCache = new UserTokenCache(context.Principal).TokenCache;
                var cca = new ConfidentialClientApplication(AzureAdB2COptions.ClientId, AzureAdB2COptions.Authority, AzureAdB2COptions.RedirectUri, new ClientCredential(AzureAdB2COptions.ClientSecret), userTokenCache, null);
                var result = await cca.AcquireTokenByAuthorizationCodeAsync(code, AzureAdB2COptions.ApiScopes.Split(' '));
                context.HandleCodeRedemption(result.AccessToken, result.IdToken);
            }

**Comment by markwest51** [comment]
hi

will close this issue, did not spot the other branch and also added the code above as it now builds.  Just got to work out now why my B2C SignUp/In is not displaying when i run.  There does not seem to be a clear guide on how to protect an API and then do the same with a React Web App so token can be passed across, well at least using .Net Core 2.0
