### ISSUE TITLE
Need help with Configuration

### ISSUE THREAD

**Issue by d1820** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#35]
I can run the code from this sample and get everything working in chrome and firefox.. I try and use my azure b2c and web app and api and nothing works, even though the code is the same minus the appSettings.  Can we get screen shots posted of all the actual Azure configuration and setup.. I have followed the steps in the read me and no luck.  i have no clue what could be missing at this point. Any help would be great.. a simple azure b2c setup is now taking 5 days?? this can not be the case else no one would be using it.  

Also how has anyone handled all the issues with Azure and self signed certs?

**Comment by gsacavdm** [comment]
It's easier for folks to help if you post your own configurations, screenshots, details about the errors your seeing, etc.

**Comment by d1820** [comment]
I guess in my mind it's more valuable that the person or persons that wrote this code example should post their screenshots of their configuration since that's the last part of the puzzle that no one really knows about as far as looking at the code. the fact that I can download this code compile it and then run the code example and everything works means that obviously there's the missing configuration that's not quite clear either in the read me or in the documentation within the code itself that would show someone else how to set this up properly from the Azure perspective. just my opinion..

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
