### ISSUE TITLE
Suggestion: Always Provide and DIY Get-Started Intro

### ISSUE THREAD

**Issue by laultman** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#40]
Samples are GREAT. But then we have to build our own project. Nobody seems to think that we need to know how to start up using the VS tools with an MVC targeting a Microsoft technology. There are a bunch of options - which do we use?

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
