### ISSUE TITLE
What is signin-oidc.

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#47]
In your repro instructions, you instruct us to set up the Reply URI to be:

Set the Reply URL to https://localhost:5000/signin-oidc.

Why?  The application launches from https://localhost:44316, so what's supposed to be listening on this port on that route?

**Comment by wyldebill** [comment]
This wasn't clear to me either from the docs.  /signin-oidc is a prebaked url in the Open Id Connect middleware that Azure AD uses.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
