### ISSUE TITLE
How to debug mis-configured setup?

### ISSUE THREAD

**Issue by phatcher** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#48]
I have a working ASP.NET MVC application that uses Azure B2C and I'm trying to make an ASP.NET Core app that uses the same tenant with no success.

The directory/policy information is likely to be correct since I copied it from the working setup but the problem I get is that I am not presented with my login screen.

What I notice is that the authentication urls are different in the MVC and .NET Core apps i.e. the MVC app (and the policy tryout) is pointing at

https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?p={Policy}...

whereas the .NET Core app goes to 

https://login.microsoftonline.com/te/{tenant}/{policy}/oauth2/v2.0/authorize?...&x-client-ver=2.1.4.0 

it comes back with a 200 from the MS site but doesn't present a login screen. I've tried adding handlers on all the other OpenIdConnect events but I receive no events.

I also get the same behaviour if I drop my tenant/policy information into the sample app, whereas the OOB I get a login screen

Ideas?

**Comment by phatcher** [comment]
Can I have some response please!

**Comment by phatcher** [comment]
@parakhj yet again no response from anyone in your team

**Comment by parakhj** [comment]
Apologies @phatcher. The URL's, while different, do the same thing. Some OIDC libraries don't like the fact that there is a non-standard parameter (the p parameter for policy), so we have to provide a URL format that has the policy in the path. 

For quicker replies, I encourage also posting on stackoverflow, using the tag 'azure-ad-b2c'.  There are a lot more people monitoring that

**Comment by phatcher** [comment]
@parakhj No if you are going to post examples here, it makes sense to support them here. Also the only question posted on SO regarding this example has no replies apart from the author.

If you are not going to support these examples directly, make it clear in the documentation page of the project.

What's not clear from the documentation is that from the .NET to the dotnetcore version you must change the reply url in the Azure B2C tenant to include "signin-oidc" i.e. if you previously had "https://localhost:44316" you must also add "https://localhost:44316/signin-oidc" for the dotnetcore client code to work

**Comment by parakhj** [comment]
The redirect URL is something you have full control over. It's just a matter of what URL the application is listening at. The .dotnetcore convention is to add the code that listens to the reply behind the path specified by /signin-oidc at the end. However, your code could handle it at the root level as well. It's just how you implement it

**Comment by phatcher** [comment]
@parakhj From what I can see yes we do have full control over the reply url, however we must append /signin-oidc to the registered url in the Azure B2C tenant, or whatever string is assigned to OpenIdConnectOptions.CallbackPath, which won't except an empty string.

So from my perspective, this is a breaking change since I didn't have to do this for the standard .NET WebApp code and you have failed to adequately document this - I say this because there are about four open issues here which are all about this problem.

When you say "your code could handle it at the root level", can you explain what you mean by this?

**Comment by parakhj** [comment]
Ah okay. Thanks for clarifying that - didn't properly acknowledge that you are migrating from your .NET webapp code. 
Sure I'll work on making the instructions more clear.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
