### ISSUE TITLE
Microsoft.Identity.Client

### ISSUE THREAD

**Issue by grahamehorner** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#49]
The Microsoft.Identity.Client package is a preview package and contains a number of classes that have duplicates in the Microsoft.IdentityModel.Client package/namespace; when/will this be corrected or is Microsoft.Identity.Client preview obsolete ?

**Comment by jmprieur** [comment]
@grahamehorner : MSAL.NET is indeed a preview package, but we are actively working on it, and it will eventually replace ADAL.NET.
For more information, please read https://aka.ms/adal-4-msal-2-preview
