### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by hungxuanho** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#50]
Hi. I'm new to Azure and OpenIdConnect. I download the web app, run it from Visual Studio 2017 and got to the login page (https://login.microsoftonline.com/fabrikamb2c.onmicrosoft.com/B2C_1_SUSI/api....)

Then, I created an Azure AD B2C web app. I updated the web app's appsettings.json as shown below. 
I published the web app to Azure. The web app's url is https://the-real-name.azurewebsites.net. 
When I go to https://the-real-name.azurewebsites.net, it redirects me to https://login.microsoftonline.com/te/mytenantxyz.onmicrosoft.com/b2c_1_siupin/oauth2/v2.0/authorize?client_id=.......
But the browser window was then just blank. After some seconds, it redirects me back to https://the-real-name.azurewebsites.net. I did not see the login page. Somebody please help me. 

appsettings.json
{
  "Authentication": {
    "AzureAdB2C": {
      "ClientId": "my-client-id",
      "Tenant": "mytenantxyz.onmicrosoft.com",
      "SignUpSignInPolicyId": "B2C_1_SiUpIn",
      "ResetPasswordPolicyId": "B2C_1_SSPR",
      "EditProfilePolicyId": "B2C_1_SiPe",
      "RedirectUri": "https://the-real-name.azurewebsites.net",
      "ClientSecret": "my-clientSecret",
      //"ApiUrl": "https://taskservice123456.azurewebsites.net/",
      //"ApiScopes": "https://mytenantxyz.onmicrosoft.com/TaskServiceAPIDemo/user_impersonation"
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  }
}

**Comment by phatcher** [comment]
@hungxuanho Have you setup the endpoint in your Azure B2C tenant to have a redirect url of https://the-real-name.azurewebsites.net/signin-oidc, the "signin-oidc" is required by the new client and is not particularly well documented

**Comment by hungxuanho** [comment]
Hi Phatcher. Many thanks for your response. Yes, putting signin-oidc at the end of the Replay URL, like this https://the-real-name.azurewebsites.net/signin-oidc,  works perfect. Thanks again, Phatcher.
