### ISSUE TITLE
Hangs during high request loads

### ISSUE THREAD

**Issue by blinkybill** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#52]
Thank you for this great sample. Has this code been tested with production loads? It would be a good idea to update the sample code to include this kind of lock handling below so if something goes wrong with entering a lock the exiting of the lock does not get attempted, further degrading performance.

var lockIsHeld = false;
try {
   try {
   }
   finally {
      rwl.EnterReadLock();
      lockIsHeld = true;
   }
 
   // Do work here
}
finally {
   if (lockIsHeld) {
      rwl.ExitReadLock();
   }
}

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
