### ISSUE TITLE
Not compatible with Microsoft.Identity.Client 2.0.0-preview

### ISSUE THREAD

**Issue by thomhubers** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#54]
The sample works with 1.1.0-preview, which is fine. However, my project used a slightly newer one and some NullReferences emerged in the MSALSessionCache.

Using 1.1.0-preview is fine for me, but I just wanted to let you know.

**Comment by asmithKinegdo** [comment]
I had the same issue.  Cost me about 10 hrs of work to figure it out.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
