### ISSUE TITLE
got secure error when I try to sign in 

### ISSUE THREAD

**Issue by peiqinli** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#57]
![image](https://user-images.githubusercontent.com/17135421/46264681-44babe00-c4d4-11e8-8dfc-f9b593e74a7f.png)

**Comment by elvogel** [comment]
Your reply URI was probably converted to `http` instead of `https`. Try adding this to the top of `OnRedirectToIdentityProvider` in `OpenIdConnectOptionsSetup`:

```csharp
if (context.ProtocolMessage.RedirectUri.Contains("http:"))
{                    
    context.ProtocolMessage.RedirectUri = context.ProtocolMessage.RedirectUri.Replace("http:", "https:");
}
```

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
