### ISSUE TITLE
User.Identity.Name is null and HttpContext.User.Claims is empty

### ISSUE THREAD

**Issue by ossentoo** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#61]
Hi,

I'm trying to implement this into my app (i.e. aspnetcore 2.2 and Azure AD).  I can login to the app via Azure AD fine.  

I have implemented OnSecurityTokenValidated so that i can check that I'm receiving token and claims correctly, which is the case.

However, for some reason, I'm receiving a blank User.Identity (although it is not null).  This means there are no claims and Name property is null.

![image](https://user-images.githubusercontent.com/7569380/51987941-65ebe500-249b-11e9-87c5-9bd70c5fb8eb.png)

It looks to me that somehow the HttpContext is not being set correctly with this data.  However, where should this be happening?  I checked the code in this repository and it's not clear what copying the login data to the HttpContext.User

This object has claims:

![image](https://user-images.githubusercontent.com/7569380/51988157-eb6f9500-249b-11e9-86b6-95f48ac0fff8.png)

IN the OnSecurityTokenValidated Method:

I have create two objects from the context:

![image](https://user-images.githubusercontent.com/7569380/51988305-45705a80-249c-11e9-88d8-86632bcef6f8.png)

the user principal is being set.
![image](https://user-images.githubusercontent.com/7569380/51988704-40f87180-249d-11e9-8b1e-d83eafd2e93b.png)

however, the context has no claims.   Also User.Identity.Name thereefore is null:

![image](https://user-images.githubusercontent.com/7569380/51988805-81f08600-249d-11e9-8488-28f330b1cd78.png)

I've also tried carrying out a manual signin, but that doesn't work either:
`
            private async Task SignInUser(TokenValidatedContext tokenValidatedContext)
            {
                var httpContext = tokenValidatedContext.HttpContext;
                var userPrincipal = tokenValidatedContext.Principal;

                await httpContext.SignOutAsync(AppSettings.CookieName);
                 await httpContext.SignInAsync(AppSettings.CookieName, userPrincipal,
                    new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddDays(1),
                        IsPersistent = false,
                        AllowRefresh = false
                    });
            }
`

Any ideas what I am doing wrong?

**Comment by TiagoBrenck** [comment]
@ossentoo I am quite confuse about your problem. Are you trying to use this B2C sample code, on an Azure AD (not B2C) scenario?

**Comment by ossentoo** [comment]
no - i am using Azure B2C.  Anyway, I managed to resolve this, so I'm going to close the issue. 

I think i may have had a bug in my own code elsewhere which caused the claims to be send correctly to this callback

**Comment by fad16papa** [comment]
@ossentoo my apologies to disturb you, I know this post was last year. My i ask how do you manage to solve this issue? Coz right now im having the same issue thank you.

**Comment by ossentoo** [comment]
hi @fad16papa. I had to work around the issue in the end. We ended up writing some functionality to request the user details we needed from b2c.  We have an access token, and so can use this to query [Microsoft Graph](https://developer.microsoft.com/en-us/graph) for the details we need.  Clunky but it works.

**Comment by yuanweilei** [comment]
@ossentoo 
Maybe you can try this code
```

public static class ApplicationBuilderExtension
    {
         public static void UseEasyAuth2(this IApplicationBuilder app)
        {
            app.Use(async (context, next) =>
            {
                // Create a user on current thread from provided header
                if (context.Request.Headers.ContainsKey("X-MS-CLIENT-PRINCIPAL-ID"))
                {
                    // Read headers from Azure
                    var azureAppServicePrincipalIdHeader = context.Request.Headers["X-MS-CLIENT-PRINCIPAL-ID"][0];
                    var azureAppServicePrincipalNameHeader = context.Request.Headers["X-MS-CLIENT-PRINCIPAL-NAME"][0];

                    var cookieContainer = new CookieContainer();
                    HttpClientHandler handler = new HttpClientHandler()
                    {
                        CookieContainer = cookieContainer
                    };
                    string uriString = $"{context.Request.Scheme}://{context.Request.Host}";
                    foreach (var c in context.Request.Cookies)
                    {
                        cookieContainer.Add(new Uri(uriString), new Cookie(c.Key, c.Value));
                    }

                    string jsonResult;
                    using (HttpClient client = new HttpClient(handler))
                    {
                        var res = await client.GetAsync($"{uriString}/.auth/me");
                        jsonResult = await res.Content.ReadAsStringAsync();
                    }

                    //parse json
                    var obj = JArray.Parse(jsonResult);

                    string user_id = obj[0]["user_id"].Value<string>(); //user_id

                    // Create claims id
                    List<Claim> claims = new List<Claim>();
                    foreach (var claim in obj[0]["user_claims"])
                    {
                        claims.Add(new Claim(claim["typ"].ToString(), claim["val"].ToString()));
                    }

                    // Set user in current context as claims principal
                    var identity = new GenericIdentity(azureAppServicePrincipalIdHeader);
                    identity.AddClaims(claims);

                    // Set current thread user to identity
                    context.User = new GenericPrincipal(identity, null);
                }

                await next.Invoke();
            });
        }
    }

```
use it in startup.cs, 
`app.UseEasyAuth2();`

**Comment by fad16papa** [comment]
Hi @ossentoo thanks for the code and effort to help highly appreciated. I was able to solve my issue by adding a  [Authorize(Roles = ("sample role"))] in every endpoint call of my API method were the roles is set via identity roles and stored it in JWT . Here is my sample code 

 [Authorize(Roles = ("sample role"))]
        [HttpPost, Route("external/api/SubmitVehicleNumberTNPermitLand/{cassToken}")]
        public async Task<IActionResult> SubmitVehicleNumberTNPermitLand(string cassToken, [FromBody] VehiclePermitInformation vehiclePermitInformation)
        {
            //Instantiate the CassResponseModel
            CassResponseModel cassResponseModel = new CassResponseModel();

            //Instatiate the CassLogs
            CassLogs cassLogs = new CassLogs();

            string response = string.Empty;
            try
            {
                //Instantiate VehicleInformationRSS and populate its properties
                VehicleInformationRSS vehicleInformationRSS = new VehicleInformationRSS();

                vehicleInformationRSS.requestType = "VHCINF";
                vehicleInformationRSS.requestId = string.Format("{0}{1}", "VHCINF", Guid.NewGuid().ToString());
                vehicleInformationRSS.requestDateTime = DateTime.Now;
                vehicleInformationRSS.vehicleNo = vehiclePermitInformation.VehicleNumber; // get the vehicle number via permit table 
                vehicleInformationRSS.location = _configuration["Location:Checkpoint"]; // get the location set via app config
                vehicleInformationRSS.permitCount = vehiclePermitInformation.PermitCount; // The total count of the permits inside per send request to CASS URI

                foreach (var item in vehiclePermitInformation.PermitNumber)
                {
                    vehicleInformationRSS.permitNo.Add(item); 
                }

                #region Call the CASS Interface Endpoint
                //use the TMSapi httpClient
                var client = _clientUser.CreateClient("CASS");

                //Retrieve the JWT toke in cookie and place it inside the header request
                //var token = Request.Cookies["Authorization"];
                client.DefaultRequestHeaders.Add("Authorization", cassToken);

                //Call the CASS URI and pass the jsonObject as POST method
                var putTask = client.PostAsJsonAsync<VehicleInformationRSS>("sample/sample", vehicleInformationRSS).Result;
                #endregion

                #region Check the response of cass interface
                cassResponseModel = putTask.Content.ReadAsAsync<CassResponseModel>().Result;
                response = cassResponseModel.ReasonCode;

                //Counter Check tries 
                int errorChecker = 0;
                int counterCheck = Convert.ToInt32(_configuration["CASSUri:counterCheck"]);

                //Check if the request == 002
                if (response == null)
                {
                    for (errorChecker = 0; errorChecker <= counterCheck; errorChecker++)
                    {
                        //Call again the CASS URI 
                        putTask = client.PostAsJsonAsync<VehicleInformationRSS>("land/permits/", vehicleInformationRSS).Result;

                        //Check if the putask is still == null
                        if (putTask != null)
                        {
                            return Ok();
                            break;
                        }
                        if (errorChecker == counterCheck)
                        {
                            return BadRequest("Cannot Connect to the CASS Interface");
                            break;
                        }
                    }
                }

                //Check if  the request == 002
                if (response.Equals("002"))
                {
                    return BadRequest("Invalid Permit Number");
                }

                //Check if the request = 001
                if (response.Equals("001"))
                {
                    return BadRequest("Invalid Vehicle Number");
                }
               
                return Ok("Process Successfull");
                #endregion
            }
            catch (Exception ex)
            {
                // Logging the error
                _logger.LogError($"Error while RSS call the CASS post request method SubmitVehicleNumberTNPermit. Exception: {ex.Message}");
                // Returning badRequest
                return BadRequest("Error while execute the SubmitVehicleNumberTNPermitLand");
            }
        }
