### ISSUE TITLE
Single-Sign Out AD B2C

### ISSUE THREAD

**Issue by joshhhz** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#67]
I have a **2 application** using a single `AD B2C` tenant. I want to _logout_ the user from both websites when the user signs out to either one of them. I'm using email for local accounts.

In `AAD`, there is a `LogoutUrl` registered on each application which receives a GET request to users currently signed in to. [Source](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#send-a-sign-out-request)

I wonder if there is workaround for `AD B2C` like in `AAD`.

**Comment by TiagoBrenck** [comment]
@jshrico would this be a solution for you?

```
await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
var scheme = User.Claims.First(x => x.Type == "tfp").Value;
await HttpContext.SignOutAsync(scheme);
```

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
