### ISSUE TITLE
Error messages in OnRemoteFailure should be url encoded before appending to query string

### ISSUE THREAD

**Issue by MonkeyTennis** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#70]
I hit an issue where the Error page could not show the details of a specific error. It transpired this was because the error message, appended to the query string, contained invalid characters to form part of a URL.

**Comment by MonkeyTennis** [comment]
Fix could be to do this on line 98 of ,\active-directory-b2c-dotnetcore-webapp\WebApp-OpenIDConnect-DotNet\OpenIdConnectOptionsSetup.cs:

context.Response.Redirect("/Home/Error?message=" + Uri.EscapeDataString(context.Failure.Message));

**Comment by TiagoBrenck** [comment]
Thanks for pointing that out.

**Comment by TiagoBrenck** [comment]
Fixed
