### ISSUE TITLE
Latest version of AAD B2C?

### ISSUE THREAD

**Issue by AryStl** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#72]
Is this sample leveraging the latest version of AAD B2C? I noticed that some parts of the code are quite old >6 months.

Or is it better to use: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC ? I noticed there is no Social Identities part there yet, any suggestions on samples or how to build it?

**Comment by DanoThom** [comment]
Total agreement on the above. With the new Azure AD B2C library and options this is desperately needed.

**Comment by TiagoBrenck** [comment]
@AryStl @DanoThom we have added a basic B2C login sample on our dotnetcore tutorial repository: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C. 
The sample is using the package, **Microsoft.AspNetCore.Authentication.AzureADB2C.UI**

If you have any suggestion for the dotnetcore B2C scenario, please open [an issue using this link](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues). We will analyse the request and plan the update. I will close this ticket for now.

Thanks
