### ISSUE TITLE
Update the repository to not use Bower

### ISSUE THREAD

**Issue by iamalexmang** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#76]
Bower came as a client-side package management solution from the older templates of ASP.NET web applications. However, since Bower is deprecated, running this sample on VS 2019 becomes difficult and renders the sample useless (jQuery isn't loading, Bootstrap isn't loading etc.).
It is therefore my opinion that this sample should be updated to the latest .NET Core version, not use Bower (but maybe LibMan instead).

**Comment by TiagoBrenck** [comment]
Would this sample be closer to what you are looking for? https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

**Comment by amang2205** [comment]
Totally!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
