### ISSUE TITLE
Update the repository to use the latest MSAL version

### ISSUE THREAD

**Issue by amang2205** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#77]
This sample is using a very old MSAL version and becomes useless as a sample or guideline for implementing Azure AD B2C. Currently, this app targets MSAL 3.0.3-preview and in the case of a simple package update to 4.2.x, the sample no longer works.

**Comment by TiagoBrenck** [comment]
The [PR](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp/pull/75) is opened already.

Thanks

**Comment by jennyf19** [comment]
@amang2205 done. we are also working on this [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C) if you're interested.
