### ISSUE TITLE
b2clogin.com for ASP.NET Core

### ISSUE THREAD

**Issue by RadOsinski** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#80]
Hello,

I would like to ask for code update for using ASP.NET Core 2.2  MVC with b2clogin.com 
According to docummentation onmicrosoft.com is not recommended:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-b2c/b2clogin.md

Additionally onmicrosoft.com cannot be used to to enable JavaScript on custom pages:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/javascript-samples

**Comment by jmprieur** [comment]
@RadOsinski : can you please try this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C.
It's part of an incremental tutorial and is about a Web App that signs-in users with B2C and uses b2cLogin

cc: @negoe @henrik-me @bgavrilMS @jennyf19

**Comment by RadOsinski** [comment]
@jmprieur Thanks! That resolve an issue!

**Comment by akourbat** [comment]
I also ran into this problem and it took me a few days looking for answers.  I suggest you change the `AzureAdB2COptions` class in the sample so that it uses `b2clogin.com` by default, otherwise access tokens are rejected by protected APIs - since most of them use `b2clogin.com` authority.

**Comment by TiagoBrenck** [comment]
@akourbat we have an updated sample here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

**Comment by akourbat** [comment]
The above example only handles log-in to a webapp, and not a scenario where webapp then accesses a back-end webapi on behalf of the user like this repo does.

**Comment by TiagoBrenck** [comment]
Oh I see. The version that you re looking for is under review: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/192

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
