### ISSUE TITLE
Words 'simple' and 'dead simple' should be removed from content.

### ISSUE THREAD

**Issue by dmitrios** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#82]
By using the above words, article will likely appear as indirectly offensive to reader by stating that subject described is 'simple' or 'dead simple'. The reader may be not familiar with subject in the article and such content implies that he/she cannot comprehend things that 'are simple'.
Using these words is also clear violation of internal product content policies that has been established at Microsoft in last 15 years.

**Comment by jennyf19** [comment]
@dmitrios Sorry to have missed this great feedback. I have made the changes. You are correct. Appreciate you taking the time to provide this feedback. If you find other places that need updating, please let us know.
